### ISSUE TITLE
How to Install this package ?

### ISSUE THREAD

**Issue by imerkle** [dgraham/identicon#1]
Im getting `identicon: command not found` . 

I installed this package from crates.

I also cloned the repository and did `cargo run` after `cargo build`

Cant get this to work.

**Comment by imerkle** [comment]
it was in `/target/debug/`

**Comment by dgraham** [comment]
Running `cargo build --release` will compile an optimized binary at `target/release/identicon`. Compiled binary [releases](https://github.com/dgraham/identicon/releases/latest) are also available for macOS.
