### ISSUE TITLE
Why depend on OpenSSL?

### ISSUE THREAD

**Issue by NfNitLoop** [dgraham/identicon#2]
What's with the dependency on openssl?

When I install identicon v0.1.1 from crates.io, it has a depdenency on openSSL. 
 <https://crates.io/crates/identicon/0.1.1/dependencies>
 
 But that doesn't seem to be the case in this project's [Cargo.toml][1]

[1]: https://github.com/dgraham/identicon/blob/master/Cargo.toml

Does this repo differ from what's published on crates.io? 

(OpenSSL is failing to build for me on Windows. But also, it seems unnecessary?)

**Comment by NfNitLoop** [comment]
Aha, I see that was removed in https://github.com/dgraham/identicon/commit/5a9d66fafd4c752e87786bc6c1273d2847cabbe8#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542

**Comment by NfNitLoop** [comment]
So should folks just install from GitHub directly?

**Comment by dgraham** [comment]
I just published a 0.2.0 version to remove the old dependencies.

**Comment by NfNitLoop** [comment]
Thanks! 🎉
