### ISSUE TITLE
Incompatible with Identicon.js?

### ISSUE THREAD

**Issue by NfNitLoop** [dgraham/identicon#3]
I currently use Identicon.js, and I'm looking for a rust implementation that I can replace it with. It looks like this is close, but ends up with a different color:

hash bytes:  2CED8F983ED00D9E9CF6D4B3487B28799F2AF470755FAA4B697DDFF7A1AC5E00

identicon.js gives:

![image](https://user-images.githubusercontent.com/339075/127423437-427fd1f8-8b08-4a37-b50a-506f947f7095.png)

But `identicon` gives:

![icon](https://user-images.githubusercontent.com/339075/127423557-81d8ad8a-341f-43e4-b2ea-14c2da616683.png)

Is this a bug?

**Comment by dgraham** [comment]
> This little library will produce the same shape and (nearly) the same color as GitHub when given the same hash value.
—https://github.com/stewartlord/identicon.js/#identiconjs

It looks like identicon.js is approximating the color. The colors used in this library match GitHub's algorithm. You can check any user's identicon with their login name in this URL https://github.com/identicons/NfNitLoop.png.

**Comment by NfNitLoop** [comment]
Ah, thanks!  I've forked, and am probably going to try to make an option to remain compatible with identicon.js. If you're interested, I can put up a PR to merge that back into your codebase. (Otherwise I'll just stay forked and use my own fork.)

**Comment by NfNitLoop** [comment]
This is available via [these commits][1].  (May be easier to view in [this PR][2], but that also includes some redundant changes.) 

[1]: https://github.com/NfNitLoop/identicon/compare/b5337a7...cc554d5
[2]: https://github.com/NfNitLoop/identicon/pull/1
